services:
  backend:
    build: ./backend
    container_name: bookstack-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/env/.env.prod
    environment:
      # Override database URL for Docker
      - DB_URL=jdbc:postgresql://db:5432/bookstack
    depends_on:
      - db
    networks:
      - bookstack-network

  frontend:
    build: ./frontend
    container_name: bookstack-frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - bookstack-network

  db:
    image: postgres:15-alpine
    container_name: bookstack-db
    ports:
      - "5432:5432"
    env_file:
      - ./backend/env/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstack-network

  prometheus:
    image: prom/prometheus:latest
    container_name: bookstack-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - bookstack-network

  grafana:
    image: grafana/grafana:latest
    container_name: bookstack-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - bookstack-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: bookstack-postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:password@db:5432/bookstack?sslmode=disable
    depends_on:
      - db
    networks:
      - bookstack-network
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: bookstack-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - bookstack-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: bookstack-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - bookstack-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: bookstack-filebeat
    user: root
    volumes:
      - ./monitoring/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
    networks:
      - bookstack-network

networks:
  bookstack-network:
    driver: bridge

volumes:
  postgres_data_dev:
  prometheus_data:
  grafana_data:
  elasticsearch_data: