version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bookstack-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/env/.env.prod
    environment:
      # Override database URL for Docker
      - DB_URL=jdbc:postgresql://db:5432/bookstack
    depends_on:
      - db
    networks:
      - bookstack-network

  frontend:
    build: ./frontend
    container_name: bookstack-frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - bookstack-network

  db:
    image: postgres:15-alpine
    container_name: bookstack-db
    ports:
      - "5432:5432"
    env_file:
      - ./backend/env/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstack-network

networks:
  bookstack-network:
    driver: bridge

volumes:
  postgres_data: