version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bookstack-backend-dev
    ports:
      - "8080:8080"
      - "35729:35729"  # For LiveReload
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    env_file:
      - ./backend/env/.env.dev
    environment:
      # Override database URL for Docker
      - DB_URL=jdbc:postgresql://db:5432/bookstack
      # Enable actuator endpoints for metrics
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
    depends_on:
      - db
    networks:
      - bookstack-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bookstack-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:8080/api
    networks:
      - bookstack-network

  db:
    image: postgres:15-alpine
    container_name: bookstack-db-dev
    ports:
      - "5432:5432"
    env_file:
      - ./backend/env/.env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - bookstack-network

  prometheus:
    image: prom/prometheus:latest
    container_name: bookstack-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - bookstack-network

  grafana:
    image: grafana/grafana:latest
    container_name: bookstack-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - bookstack-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: bookstack-postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:password@db:5432/bookstack?sslmode=disable
    depends_on:
      - db
    networks:
      - bookstack-network

networks:
  bookstack-network:
    driver: bridge

volumes:
  postgres_data_dev:
  prometheus_data:
  grafana_data: