version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bookstack-backend-dev
    ports:
      - "8080:8080"
      - "35729:35729"  # For LiveReload
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    env_file:
      - ./backend/env/.env.dev
    environment:
      # Override database URL for Docker
      - DB_URL=jdbc:postgresql://db:5432/bookstack
    depends_on:
      - db
    networks:
      - bookstack-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bookstack-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:8080/api
    networks:
      - bookstack-network

  db:
    image: postgres:15-alpine
    container_name: bookstack-db-dev
    ports:
      - "5432:5432"
    env_file:
      - ./backend/env/.env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - bookstack-network

networks:
  bookstack-network:
    driver: bridge

volumes:
  postgres_data_dev: